[package]
name = "localhost"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
mio = { version = "=0.8.9", features = ["net"] }

[dependencies.uuid]
version = "1.12.0"
features = [
    "v4",
    "v7",
    "js",
]
