[log_files]
error_log = "logs/errors.log"
access_log = "logs/access.log"
events_limit = 128

[http]
access_log_format = "$remote_addr - $remote_user [$time_local] - $method - $status $bytes_sent"
timeout = 3000 # seconds
size_limit = 5000 # kb

[http.server]
ip_addr = "127.0.0.2"
hostname = "mylocalhost"
ports = [80, 81]
root_directory = "www/"
error_path = "www/error"
default_file = "www/index.html"
access_log = "logs/access.log"
cgi_file_format = ".py"
upload_limit = 5000
accepted_methods = ["GET"]
directory_listing = true
